### PR TITLE
changes for Mac OS X build against Quartz (NOT X-Quartz)

### PR DESCRIPTION
**Pull request by markusdd**
DO NOT MERGE THIS. For investigation of #43 

Hi Tony, 

these are the changes I had to do to get it to compile, I extended README.md with my rough steps.

We should strive to get it building against GTK3 Quartz backend, as XQuartz is outdated and further development is unclear. So some of the MAC specific defines etc. will need some tuning.

Let me know if I should try anything out, I am more than happy to try building stuff for you.

BR
Markus

### CODE REVIEW

**Comment by umarcor** [comment]
> DO NOT MERGE THIS. For investigation of #43

You can mark this PR as draft, which will prevent it from being merged. See the option at the right sidebar.

**Comment by umarcor** [comment]
> Let me know if I should try anything out, I am more than happy to try building stuff for you.

I can help setting MacOS CI jobs, so it is tested publicly.

**Comment by markusdd** [comment]
> > DO NOT MERGE THIS. For investigation of #43
> 
> You can mark this PR as draft, which will prevent it from being merged. See the option at the right sidebar.

You have a screenshot? I do not see this option.



> > Let me know if I should try anything out, I am more than happy to try building stuff for you.
> 
> I can help setting MacOS CI jobs, so it is tested publicly.

Once we have the code issues figures out that would be great going forward!

**Comment by gtkwave** [comment]
Yes, if you'd like to try building stuff, that would be great. I'm quite busy with other things at the moment and don't know when I'll be able to set up a GTK3 build environment under a VM for my own personal testing.

-Tony


     On Sunday, February 28, 2021, 10:37:11 AM EST, Unai Martinez-Corral <notifications@github.com> wrote:  
 
 



Let me know if I should try anything out, I am more than happy to try building stuff for you.


I can help setting MacOS CI jobs, so it is tested publicly.

**Comment by markusdd** [comment]
Yes, no problem.
As shown I pretty much have a 'kind of' functioning env right now, but to be honest I am rather lost when it comes to the commented out sections. I am not familiar with GTK internals very much and same goes for X11, so I can hardly fix these sections properly. I can certainly try to find out why configure still complains about TCL and why XZ is not being picked up.

**Comment by markusdd** [comment]
ok, so I updated the README.md

once LZMA (XZ) and TCL are found properly, the check-mark issue in the menues are gone and --disable-xz is no longer necessary.

now only the `GTKWAVE | MESSAGE: gtk_window_add_accel_group: assertion 'GTK_IS_WINDOW (window)' failed`
message remains and we need to find a solution for the commented out code sections in main.c and twinwave.c.

**Comment by umarcor** [comment]
@markusdd see https://github.com/umarcor/gtkwave/commit/0be7e05ad9e343e39d6cdd888a11e20236d005de. That's how to add the commands to CI, instead of the README.

Unfortunately, macos-11.0 is not available for everyone yet: https://github.com/actions/virtual-environments/issues/2486.

**Comment by markusdd** [comment]
@umarcor thanks a lot, I have pulled this in here

**Comment by umarcor** [comment]
@markusdd nice! Note that it won't work in this PR, because the workflow is setup to be executed on `push`, but not `pull_request`: https://github.com/gtkwave/gtkwave/blob/master/.github/workflows/build.yml#L4. Therefore, you will see CI runs in your fork: https://github.com/markusdd/gtkwave/actions. You might need to enable it the first time. Example run in my fork: https://github.com/umarcor/gtkwave/runs/2012360522?check_suite_focus=true.

**Comment by markusdd** [comment]
ok, thanks for the hint.
I'm a gitlab user on my daily job so I'm not very familiar with all the inner working of github xD

**Comment by markusdd** [comment]
Ok nice, so now we have a running CI with complete build.

Of course the main.c and twinwave.c are still 'hacked' without a real fix.

**Pull request closed without merging**
