### PR TITLE
Update macos support

### PR DESCRIPTION
**Pull request by randomplum**
This change updates macos support.

### CODE REVIEW

**Comment by rfuest** [comment]
How is the menu bar handled in the macOS build? In the screenshots in #250 there seems to be a menu bar inside the window, but there is also some code to use the global macOS menubar. I don't think there should be both and only using the global menu bar should be more familiar to macOS users.

Regarding the `getopt` files: I think we can remove the local copies of getopt entirely and rely on the system files instead. Every platform we compile for should have the necessary functions and at some point we will move from getopt to using the glib command line handling anyway.

**Comment by randomplum** [comment]
> How is the menu bar handled in the macOS build? In the screenshots in #250 there seems to be a menu bar inside the window, but there is also some code to use the global macOS menubar. I don't think there should be both and only using the global menu bar should be more familiar to macOS users.
> 
> Regarding the `getopt` files: I think we can remove the local copies of getopt entirely and rely on the system files instead. Every platform we compile for should have the necessary functions and at some point we will move from getopt to using the glib command line handling anyway.


With full mac integration enabled it looks like that (different icons are due to a different machine with gtk theme set to not default) :

image

Previous screenshot was from early experiments without any specific macos code enabled, then the menu bar was only in the application (gtk on macos nicely handles both ways)


ok, I'll remove the getopt files. I disabled them for mac since clang 15 with default flags really doesn't like the old-school function parameter types definitions.

**Comment by rfuest** [comment]
`gnu-getopt.h` can also be removed and replaced by `#include <getopt.h>`.

**Comment by randomplum** [comment]
> `gnu-getopt.h` can also be removed and replaced by `#include <getopt.h>`.

done

**Review by rfuest — APPROVED** [review]
Looks good.

**Pull request merged**
