### PR TITLE
Queue draw on hslider change

### PR DESCRIPTION
**Pull request by rfuest**
This is an attempt to fix the issue reported in #61.

### CODE REVIEW

**Comment by Tang-Haojin** [comment]
Thank you very much, and it works for me almost perfectly.

However, when I try to open my fst file directly by `gtkwave dump.fst`, and then `File -> Read Save File`, the GUI refresh issue still exists when I scrolling vertically with my mouse and focus on `Signals` Groupbox.

This issue would not happen if I type `gtkwave` and open a new tab manually.

I am not sure if it is reproducible on other device.

**Comment by rfuest** [comment]
> However, when I try to open my fst file directly by `gtkwave dump.fst`, and then `File -> Read Save File`, the GUI refresh issue still exists when I scrolling vertically with my mouse and focus on `Signals` Groupbox.
> 
> This issue would not happen if I type `gtkwave` and open a new tab manually.
> 
> I am not sure if it is reproducible on other devices.

Thanks for your feedback. I was able to reproduce the problem in Windows. I've updated the PR to force a redraw of the widgets in some additional cases.

The fact that this issue doesn't exist in a new tab is interesting and I don't have an explanation for this at the moment. But I'm currently working on some refactoring of the drawing code, which should make the redrawing more robust.

**Comment by rfuest** [comment]
I'm closing this in favor of #80, which includes the same fix.

**Comment by gtkwave** [comment]
OK, thanks.  #80 should be a part of master now.  I checked in this one which is a minor compile fix on older centos7/rhel7 machines:
To https://github.com/gtkwave/gtkwave
   d2f92e3..9038a5f  master -> master

-Tony

    On Tuesday, October 5, 2021, 1:03:42 PM EDT, Ralf Fuest ***@***.***> wrote:  
 
 


I'm closing this in favor of #80, which includes the same fix.


—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Pull request closed without merging**
