### PR TITLE
Update io.github.gtkwave.GTKWave.metainfo.xml

### PR DESCRIPTION
**Pull request by aklsh**
Follow up on discussion in https://github.com/flathub/io.github.gtkwave.GTKWave/pull/7.

### CODE REVIEW

**Review by rfuest — APPROVED** [review]
LGTM, thanks for the PR.

@tbybell: Could you merge this into the LTS version and add the the missing release descriptions?

**Comment by tbybell** [comment]
Specifically, what are you asking for?  Adds to gtkwave.appdata.xml?  Overlay io.github.gtkwave.GTKWave.metainfo.xml on top of the existing gtkwave.appdata.xml with missing release descriptions added, etc?  Thanks.

**Comment by rfuest** [comment]
Sorry for the confusion, I didn't remember that I had renamed the file. The `...appdata.xml` naming is deprecated and I would suggest that you also rename the file in the LTS version and then apply this patch.

**Comment by tbybell** [comment]
Done, thanks.

-Tony

560:/home/bybell/gtkwave/code> svn commit
Password: 
Sending        gtkwave3/ChangeLog
Sending        gtkwave3/share/appdata/Makefile.am
Sending        gtkwave3/share/appdata/Makefile.in
Deleting       gtkwave3/share/appdata/gtkwave.appdata.xml
Adding  (bin)  gtkwave3/share/appdata/io.github.gtkwave.GTKWave.metainfo.xml
Sending        gtkwave3-gtk3/ChangeLog
Sending        gtkwave3-gtk3/share/appdata/Makefile.am
Sending        gtkwave3-gtk3/share/appdata/Makefile.in
Deleting       gtkwave3-gtk3/share/appdata/gtkwave.appdata.xml
Adding  (bin)  gtkwave3-gtk3/share/appdata/io.github.gtkwave.GTKWave.metainfo.xml
Transmitting file data ........
Committed revision 1650.

**Pull request merged**
