### PR TITLE
Refactor signal list into a GTK widget

### PR DESCRIPTION
**Pull request by rfuest**
This PR refactors the signal list code into a GTK widget. It's still a WIP, but I would appreciate some initial feedback if this is going in the right direction. Some code is still commented out and needs to be fixed. But I would like to know if I have broken anything I didn't notice yet or if I have changed some intentional behavior that would break someones workflow.

The reason for implementing this is to try to make maintenance of the signal list code easier. I merge all code related to this widget into a single source file instead of spreading it across multiple files. All drawing operations are now performed in `draw` (or `expose_event` for GTK2) instead of being spread across multiple signal handlers.

The signal list now also manages the adjustment for the vertical scrolling. This makes it easier to keep the state in sync and implement additional API like: `gw_signal_list_scroll_to_trace(list, trace);` to make sure a trace is visible without having to manually count traces and modify the vertical adjustment directly.

I've also updated the behavior a bit:
- DnD and the context menu now distinguish between clicks on a selected and a unselected trace.
  If the user right clicks on an unselected trace the selection will be changed to that trace. The old behavior could be surprising for new users, because other UIs normally show the context menu for the item under the cursor.
  Dragging selected traces now also works without having to use the middle mouse button.
- Traces in the signal list can now be duplicated using DnD while holding CTRL.
- SHIFT+CRTL can now be used together to select multiple blocks of traces at once (see demo below).
- The automatic scrolling during DnD has changed.
  It was previously possible to scroll the signal list by simply dragging a signal from the SST up or down without even touching the signal list with the cursor. Now the list only scrolls if the cursor is above the first or last two traces in the list. This might need some time to get used to but is a cleaner approach IMO.
- The drop target position were moved by down by 1/2 trace height.
  This makes it easier to drop traces above or below an existing trace. If you aim the cursor at the gap between the two traces the traces will now be inserted at the correct position.

Demo of the updated selection and DnD behavior:

https://user-images.githubusercontent.com/226123/132392491-495bc499-c8b4-4d94-9976-a83f21632449.mp4

Known bugs:
- [ ] DnD from other instances or files doesn't work yet
- [x] Appending a trace from the SST doesn't scroll to the right position

### CODE REVIEW

**Comment by gtkwave** [comment]
I had some time to experiment with it briefly yesterday.  Some notes...  

Keyboard focus for functions such as ctrl-A to select all seems frozen to the signal widget rather than also working in the SST.I noticed a lot of visual noise when resizing the window in gtk3 using a resizing widget where the entire window would flash solid black while I was moving the cursor around doing the resizing.  In gtk2 this looks OK.

I didn't try the --dark command line option when compiled against gtk3 to ensure the color scheme is as expected, so you might want to try that.
For those attempting to experiment with this, you also need to regenerate the ./configure file by running ./autogen.sh before the ./configure script, otherwise the new widget code (signal-list.c) won't compile in.

-Tony



    On Tuesday, September 7, 2021, 2:54:33 PM EDT, Ralf Fuest ***@***.***> wrote:  
 
 
This PR refactors the signal list code into a GTK widget. It's still a WIP, but I would appreciate some initial feedback if this is going in the right direction. Some code is still commented out and needs to be fixed. But I would like to know if I have broken anything I didn't notice yet or if I have changed some intentional behavior that would break someones workflow.

The reason for implementing this is to try to make maintenance of the signal list code easier. I merge all code related to this widget into a single source file instead of spreading it across multiple files. All drawing operations are now performed in draw (or expose_event for GTK2) instead of being spread across multiple signal handlers.

The signal list now also manages the adjustment for the vertical scrolling. This makes it easier to keep the state in sync and implement additional API like: gw_signal_list_scroll_to_trace(list, trace); to make sure a trace is visible without having to manually count traces and modify the vertical adjustment directly.

I've also updated the behavior a bit:
   
   - DnD and the context menu now distinguish between clicks on a selected and a unselected trace.   
If the user right clicks on an unselected trace the selection will be changed to that trace. The old behavior could be surprising for new users, because other UIs normally show the context menu for the item under the cursor.   
Dragging selected traces now also works without having to use the middle mouse button.
   - Traces in the signal list can now be duplicated using DnD while holding CTRL.
   - SHIFT+CRTL can now be used together to select multiple blocks of traces at once (see demo below).
   - The automatic scrolling during DnD has changed.   
It was previously possible to scroll the signal list by simply dragging a signal from the SST up or down without even touching the signal list with the cursor. Now the list only scrolls if the cursor is above the first or last two traces in the list. This might need some time to get used to but is a cleaner approach IMO.
   - The drop target position were moved by down by 1/2 trace height.   
This makes it easier to drop traces above or below an existing trace. If you aim the cursor at the gap between the two traces the traces will now be inserted at the correct position.

Demo of the updated selection and DnD behavior:
 Peek.2021-09-07.20-18.mp4  
Known bugs:
   
   - DnD from other instances or files doesn't work yet
   - Appending a trace from the SST doesn't scroll to the right position

You can view, comment on, or merge this pull request online at:

  https://github.com/gtkwave/gtkwave/pull/80

Commit Summary
   
   - Refactor signal list into a GTK widget

File Changes
   
   -  M gtkwave3-gtk3/src/color.c (4) 
   -  M gtkwave3-gtk3/src/color.h (1) 
   -  M gtkwave3-gtk3/src/edgebuttons.c (4) 
   -  M gtkwave3-gtk3/src/globals.c (31) 
   -  M gtkwave3-gtk3/src/globals.h (21) 
   -  M gtkwave3-gtk3/src/hiersearch.c (16) 
   -  M gtkwave3-gtk3/src/logfile.c (3) 
   -  M gtkwave3-gtk3/src/main.c (19) 
   -  M gtkwave3-gtk3/src/markerbox.c (4) 
   -  M gtkwave3-gtk3/src/menu.c (281) 
   -  M gtkwave3-gtk3/src/menu.h (1) 
   -  M gtkwave3-gtk3/src/print.c (41) 
   -  M gtkwave3-gtk3/src/ptranslate.c (13) 
   -  M gtkwave3-gtk3/src/savefile.c (4) 
   -  M gtkwave3-gtk3/src/search.c (19) 
   -  A gtkwave3-gtk3/src/signal_list.c (1104) 
   -  A gtkwave3-gtk3/src/signal_list.h (35) 
   -  M gtkwave3-gtk3/src/signalwindow.c (2161) 
   -  M gtkwave3-gtk3/src/signalwindow.h (4) 
   -  M gtkwave3-gtk3/src/strace.c (12) 
   -  M gtkwave3-gtk3/src/tcl_commands.c (70) 
   -  M gtkwave3-gtk3/src/tcl_helper.c (6) 
   -  M gtkwave3-gtk3/src/translate.c (14) 
   -  M gtkwave3-gtk3/src/treesearch.c (53) 
   -  M gtkwave3-gtk3/src/treesearch.h (4) 
   -  M gtkwave3-gtk3/src/ttranslate.c (20) 
   -  M gtkwave3-gtk3/src/vcd_partial.c (15) 
   -  M gtkwave3-gtk3/src/wavewindow.c (350) 
   -  M gtkwave3-gtk3/src/wavewindow.h (2) 

Patch Links:
   
   - https://github.com/gtkwave/gtkwave/pull/80.patch
   - https://github.com/gtkwave/gtkwave/pull/80.diff

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by rfuest** [comment]
Thanks for the initial feedback.

> Keyboard focus for functions such as ctrl-A to select all seems frozen to the signal widget rather than also working in the SST.

Added to my TODO list.

> I  noticed a lot of visual noise when resizing the window in gtk3 using a resizing widget where the entire window would flash solid black while I was moving the cursor around doing the resizing.  In gtk2 this looks OK.

That's interesting. In my experience the new version resulted in less flicker, e.g. when you drag traces. Which platform did you test on? I've only tested it on Linux with X11.

> I didn't try the --dark command line option when compiled against gtk3 to ensure the color scheme is as expected, so you might want to try that.

The `Time` header was missing in the master version and is also missing in the new version. But otherwise it seems to work.

> For those attempting to experiment with this, you also need to regenerate the ./configure file by running ./autogen.sh before the ./configure script, otherwise the new widget code (signal-list.c) won't compile in.

I meant to mention this myself but forgot. I decided not to include the `autogen.sh` changes at this point, because I'm using a different version of the autotools and running `autogen.sh` did create a lot of noise and made the PR even larger than it already is.

**Comment by gtkwave** [comment]
> Which platform did you test on? I've only tested it on Linux with X11.
Centos7 with X11, Gnome Classic as the window manager.

-Tony

    On Wednesday, September 8, 2021, 2:50:02 PM EDT, Ralf Fuest ***@***.***> wrote:  
 
 


Thanks for the initial feedback.


Keyboard focus for functions such as ctrl-A to select all seems frozen to the signal widget rather than also working in the SST.


Added to my TODO list.


I noticed a lot of visual noise when resizing the window in gtk3 using a resizing widget where the entire window would flash solid black while I was moving the cursor around doing the resizing. In gtk2 this looks OK.


That's interesting. In my experience the new version resulted in less flicker, e.g. when you drag traces. Which platform did you test on? I've only tested it on Linux with X11.


I didn't try the --dark command line option when compiled against gtk3 to ensure the color scheme is as expected, so you might want to try that.


The Time header was missing in the master version and is also missing in the new version. But otherwise it seems to work.


For those attempting to experiment with this, you also need to regenerate the ./configure file by running ./autogen.sh before the ./configure script, otherwise the new widget code (signal-list.c) won't compile in.


I meant to mention this myself but forgot. I decided not to include the autogen.sh changes at this point, because I'm using a different version of the autotools and running autogen.sh did create a lot of noise and made the PR even larger than it already is.

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by rfuest** [comment]
I think this PR should be ready to review now. The recent changes should fix several drag and drop issues that existed in the master version:
- Dragging a trace into another program was generating an invalid URI list.
  This caused the target application (e.g. gedit) to open a file with the generated TCL code as the filename. I've fixed this by using a custom type to represent Gtkwave TCL data.
- I've moved the drop target for URI lists from the signal list and waveform display widgets to the window.
  This makes it easier to open files by dropping them onto the application. Other applications, e.g. gedit, seem to follow the same pattern. This change also simplifies the code a bit, because it is no longer necessary to try to parse the DnD data as both a URI list and TCL to determine the type of data. 
-  In the master branch it is possible to start a drag from the SST to the signal list anywhere in the `sig_view` widget.
  This means that it was possible to start dragging from the blank space below the last signal in the list, even if no trace was selected.
- Dragging traces between windows did crash the source window in Wayland.
- Dragging a trace from the signal list into an empty window did cause a segfault.

Remaining issues:
- Dropping traces onto the waveform display isn't currently possible.
  I would like to fix this when I implement a similar PR to this for the waveform display.
- I wasn't able to reproduce the visual noise you described.
- MacOS is untested.

**Comment by gtkwave** [comment]
I integrated all the changes and bumped the rev up to 3.4.0 in revision control.
One thing though is keyboard focus for menu hotkeys vs entry of text in various entryboxes.  Do you remember what the fix was for that.  I either triggered it somehow or missed something when cloning your updates back and forth between two revision control systems.  I don't think I did that, but who knows.

The long and short is if I type in something like the letter "o", "h", etc. it triggers the menu hotkey rather than allows entry in the entrybox.

-Tony

    On Tuesday, October 5, 2021, 1:02:35 PM EDT, Ralf Fuest ***@***.***> wrote:  
 
 


I think this PR should be ready to review now. The recent changes should fix several drag and drop issues that existed in the master version:
   
   - Dragging a trace into another program was generating an invalid URI list.   
This caused the target application (e.g. gedit) to open a file with the generated TCL code as the filename. I've fixed this by using a custom type to represent Gtkwave TCL data.
   - I've moved the drop target for URI lists from the signal list and waveform display widgets to the window.   
This makes it easier to open files by dropping them onto the application. Other applications, e.g. gedit, seem to follow the same pattern. This change also simplifies the code a bit, because it is no longer necessary to try to parse the DnD data as both a URI list and TCL to determine the type of data.
   - In the master branch it is possible to start a drag from the SST to the signal list anywhere in the sig_view widget.   
This means that it was possible to start dragging from the blank space below the last signal in the list, even if no trace was selected.
   - Dragging traces between windows did crash the source window in Wayland.
   - Dragging a trace from the signal list into an empty window did cause a segfault.

Remaining issues:
   
   - Dropping traces onto the waveform display isn't currently possible.   
I would like to fix this when I implement a similar PR to this for the waveform display.
   - I wasn't able to reproduce the visual noise you described.
   - MacOS is untested.

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Pull request merged**
