### PR TITLE
Mac GTK3 build

### PR DESCRIPTION
**Pull request by jevinskie**
Mac sort of works with gtk3, hidpi works out of the box, icons are missing and cursor scrubbing has lots of jank.

Need cleanup, opening PR for CI testing.

### CODE REVIEW

**Comment by jevinskie** [comment]
WAVE_USE_XID used in #44 (didn't notice my duplicated work until now) looks like the proper way to disable the ports/sockets.

**Comment by jevinskie** [comment]
Just remembered I committed this without running autogen.sh so it will fail CI.

**Comment by gtkwave** [comment]
My "Mac" is Snow Leopard with GTK2 running in a VM, so I'd need someone else to verify the suitability of any proposed GTK3 patches.

-Tony
     On Thursday, June 24, 2021, 12:37:29 PM EDT, Jevin Sweval ***@***.***> wrote:  
 
 
Mac sort of works with gtk3, hidpi works out of the box, icons are missing and cursor scrubbing has lots of jank.

Need cleanup, opening PR for CI testing.

You can view, comment on, or merge this pull request online at:

  https://github.com/gtkwave/gtkwave/pull/67

Commit Summary
   
   - mac sort of works with gtk3, hidpi works out of the box, icons are missing and cursor scrubbing has lots of jank

File Changes
   
   -  M gtkwave3-gtk3/configure.ac (4) 
   -  M gtkwave3-gtk3/src/main.c (2) 
   -  M gtkwave3-gtk3/src/twinwave.c (13) 

Patch Links:
   
   - https://github.com/gtkwave/gtkwave/pull/67.patch
   - https://github.com/gtkwave/gtkwave/pull/67.diff

**Comment by jevinskie** [comment]
After reading the issue I might take a stab at seeing how much work a gtk4 port is vs trying to improve gtk3 perf. I’ve seen the same hot traces on my machine. =\

**Comment by gtkwave** [comment]
I don't know how involved a GTK3->4 port would be as I haven't attempted it. Going from GTK2->3 was a solid month of work around the end of 2017 when I was on holiday break, with most of those problems involving completely different event models, widgets migrating to needing to use a model-value-controller approach, etc. I don't know how the case is from GTK3->4.

-Tony


     On Friday, June 25, 2021, 09:51:58 PM EDT, Jevin Sweval ***@***.***> wrote:  
 
 


After reading the issue I might take a stab at seeing how much work a gtk4 port is vs trying to improve gtk3 perf. I’ve seen the same hot traces on my machine. =\

**Comment by umarcor** [comment]
@jevinskie current CI is not executed for PRs, and it does not include a macos job.

I compared this PR with #44 and put the common/equivalent modifications in a branch, so that all of them are executed in CI. Please, see:

- https://github.com/umarcor/gtkwave/tree/macos
- https://github.com/umarcor/gtkwave/tree/jev/mac
- https://github.com/umarcor/gtkwave/tree/markus/gtk3-mac

Branch macos fails. However, jev/mac and markus/gtk3-mac are successful. Both of those are a single commit behind macos each.
Could you please have a look at the differences in those two commits?

**Pull request closed without merging**
